services:
  db:
    image: postgres:alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: tess
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
