services:
  db:
    image: postgres:alpine
    container_name: my_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  zabbix-db:
    image: postgres:alpine
    container_name: zabbix_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${ZABBIX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZABBIX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZABBIX_POSTGRES_DB}
    volumes:
      - zabbix_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    container_name: zabbix_server
    env_file:
      - .env
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: ${ZABBIX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZABBIX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZABBIX_POSTGRES_DB}
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    container_name: zabbix_web
    env_file:
      - .env
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: ${ZABBIX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZABBIX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZABBIX_POSTGRES_DB}
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  zabbix_db_data:
