# Generated by Django 5.2.3 on 2025-06-20 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('allocated', 'Allocated'), ('under_maintenance', 'Under Maintenance'), ('disposed', 'Disposed')], db_index=True, max_length=50)),
                ('depreciation_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('guidelines', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['category'], name='itam_asset_categor_5b4551_idx'), models.Index(fields=['status'], name='itam_asset_status_51e171_idx')],
            },
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('decommission_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='itam.asset')),
            ],
            options={
                'verbose_name_plural': 'Disposals',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_to', models.CharField(max_length=255)),
                ('assignment_date', models.DateTimeField()),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='itam.asset')),
            ],
            options={
                'verbose_name_plural': 'Allocations',
                'ordering': ['-assignment_date'],
                'indexes': [models.Index(fields=['asset'], name='itam_alloca_asset_i_253d96_idx')],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audited_by', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('audit_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='itam.asset')),
            ],
            options={
                'verbose_name_plural': 'Audits',
                'ordering': ['-audit_date'],
                'indexes': [models.Index(fields=['asset'], name='itam_audit_asset_i_5e93da_idx')],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_key', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('vendor', models.CharField(max_length=255)),
                ('contract_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='itam.asset')),
            ],
            options={
                'verbose_name_plural': 'Licenses',
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['asset'], name='itam_licens_asset_i_b7ea7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='itam.asset')),
            ],
            options={
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-maintenance_date'],
                'indexes': [models.Index(fields=['asset'], name='itam_mainte_asset_i_748820_idx')],
            },
        ),
    ]
