# Generated by Django 5.2.3 on 2025-06-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('debit', models.FloatField(default=0.0)),
                ('credit', models.FloatField(default=0.0)),
                ('transaction_date', models.DateTimeField()),
            ],
        ),
    ]
