# Generated by Django 5.2.3 on 2025-06-19 07:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='closing_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ledger',
            name='opening_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('items', models.ManyToManyField(blank=True, to='finance.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.purchaseinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('items', models.ManyToManyField(blank=True, to='finance.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('items', models.ManyToManyField(blank=True, to='finance.item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='finance.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('items', models.ManyToManyField(blank=True, to='finance.item')),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='finance.proformainvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('transport_mode', models.CharField(blank=True, max_length=50)),
                ('vehicle_number', models.CharField(blank=True, max_length=100)),
                ('transporter_name', models.CharField(blank=True, max_length=255)),
                ('origin_address', models.TextField(blank=True)),
                ('destination_address', models.TextField(blank=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bills', to='finance.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.salesinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
